language: node_js
node_js:
  - 'node'
script: npm run build
deploy:
  provider: script
  script: npm run deploy
env:
  global:
    - GH_REF: github.com/Liduska/krabickaweb.git
    - secure: nf2ug/SkpRuJp7u02vpC4qumDPjUiJr5HD/BZcp2JxaycpRZ0X+SiDLqefhobpoWeSInvrGgQ1dvkobvLFBvuCL5qJbfNAV9BUVccfFQKY7xGDzkuvZvSsJ40QuxRtDTfV6tYVVAIUkJZnVtUf6zemm9wkio04pmdWXRAO3L9kj2VBkJv0qd4OMB/ZQEPJlJW6yPccXtt0BjwyFNipBDyCO/4Ybmn5sch9RZsE1Rsm4HUH2ZnVgAcdxDeda/j7kScnDPTFrES0ol8I/b7xemICxh3iMgO+n5QUYa8VSZJQpt36K2ISFg8/4SS1XH2OxMq2GBAhFMj9Ss83bKTABfx6sWQu5sE6I6I5dujgaBcsBkK4O0Z0Xp++IRXwjhClYMQkdXT4+QNbpfQpSGF/CBp4aJ9xNYaqndAAxLI68PeoRwKcCffZ/yrP7usPjz/sRaOUP2Z87duaBw+xtvKW9xNdMzd6rhp/SJsnG8vISw0RaJUgBQiK0oq1H6HnQIMDvF7mifNDyYpJOc4vBcCE8IAkja9Gs2oziIT0WcYN9uL2+EuZs9ZgevW8Mx4Xo6l09ID7JjIJ9WRFaHoLE7KzJTOSSf54VNW6lZBKjBglGg04FqpovmTUmbKsnV5NeqMA0Uuze+EYLl+hdikF7KGn57ue0kG3uEnmJ2ytR5YHQTVlI=
